feat(ci): add new job to check coding style

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -12,7 +12,7 @@ env:
 
 jobs:
   check_repository:
-    name: Check Repository to Start Jobs
+    name: check repository to start jobs
     runs-on: ubuntu-latest
     outputs:
       target: ${{ steps.new_output.outputs.value }}
@@ -20,7 +20,7 @@ jobs:
       - name: checkout@v4
         uses: actions/checkout@v4
 
-      - name: Check Target Repository
+      - name: check target repository
         id: new_output
         run: |
           temp=$(echo $MIRROR_URL | cut -d ':' -f 2 | sed "s/\.git//")
@@ -32,39 +32,39 @@ jobs:
           echo "value=0" >> "$GITHUB_OUTPUT"
           exit 0
 
-  # check_coding_style:
-  #   name: Check Any Coding Style Errors
-  #   needs: [check_repository]
-  #   if: ${{ needs.check_repository.outputs.target == 0 }}
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: checkout@v4
-  #       uses: actions/checkout@v4
+  check_coding_style:
+    name: check any coding style errors
+    needs: [check_repository]
+    if: ${{ needs.check_repository.outputs.target == 0 }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
 
-  #     - name: Run Coding-Style-Checker
-  #       run: check.sh $(pwd) $(pwd)
+      - name: install dependencies
+        run: |
+          apt update && apt install -y python3-pip
+          pip install --break-system-packages cpplint
+          chmod +x ./scripts/cpp_style_checker.sh
 
-  #     - name: Check Any Error
-  #       run: |
-  #         cat coding-style-reports.log | while read line; do
-  #           TYPE=$(echo $line | cut -d ':' -f 3 | cut -c 2-)
-  #           temp=$(echo $line | cut -d ':' -f 1)
-  #           NAME=$(echo $temp | cut -d '/' -f 2)
-  #           LINE=$(echo $line | cut -d ':' -f 2)
-  #           NBR=$(echo $line | cut -d ':' -f 4)
-  #           ERROR=$(printf "%s coding style error" "$TYPE")
-  #           echo "::error file=$NAME,line=$LINE,title=$ERROR::$NBR"
-  #         done
-  #         if [ -s coding-style-reports.log ]; then
-  #           exit 1
-  #         else
-  #           exit 0
-  #         fi
+      - name: check coding style
+        run: |
+          ./scripts/cpp_style_checker.sh
+
+      - name: verify cpp coding style
+        run: |
+          if [ -s coding-style-cpp-reports.log ]; then
+            echo "CPP coding style errors found. See coding-style-cpp-reports.log for details."
+            cat coding-style-cpp-reports.log
+            exit 1
+          else
+            echo "No CPP coding style errors found."
+          fi
 
   push_to_mirror:
-    name: Push to Target Repository
+    name: push to target repository
     needs: [check_coding_style]
-    if: ${{ github.event_name == 'push' }} && ${{ needs.check_repository.outputs.target == 0 }}
+    if: ${{ github.event_name == 'push' }}
     environment: RTYPE
     runs-on: ubuntu-latest
     steps:
